version: v1
project: gitpod-191109
environment: production
gcpSACredFile: /gcp-sa/credentials.json
network: gitpod-prod
dnsZone: gitpod-io
metaClusters:
- name: prod-meta-eu00
  region: europe-west1
- name: prod-meta-us01
  region: us-west-1
workspaceClusters:
- region: europe-west1
  prefix: eu
  governedBy: prod-meta-eu01
  create: true
  type: gke
- region: us-east1
  prefix: us
  governedBy: prod-meta-us01
  create: true
  type: gke
